/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class solid_ren_ffmpeg_FFmpegInfo */

#ifndef _Included_solid_ren_ffmpeg_FFmpegInfo
#define _Included_solid_ren_ffmpeg_FFmpegInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     solid_ren_ffmpeg_FFmpegInfo
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_solid_ren_ffmpeg_FFmpegInfo_urlprotocolinfo
  (JNIEnv *, jclass);

/*
 * Class:     solid_ren_ffmpeg_FFmpegInfo
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_solid_ren_ffmpeg_FFmpegInfo_avformatinfo
  (JNIEnv *, jclass);

/*
 * Class:     solid_ren_ffmpeg_FFmpegInfo
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_solid_ren_ffmpeg_FFmpegInfo_avcodecinfo
  (JNIEnv *, jclass);

/*
 * Class:     solid_ren_ffmpeg_FFmpegInfo
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_solid_ren_ffmpeg_FFmpegInfo_avfilterinfo
  (JNIEnv *, jclass);

/*
 * Class:     solid_ren_ffmpeg_FFmpegInfo
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_solid_ren_ffmpeg_FFmpegInfo_configurationinfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
